### ISSUE TITLE
Suggestion: Replace or remove unneccessary form tags

### ISSUE THREAD

**Issue by seevee** [theresaoh/blogz#1]
Two of the templates include form tags without any input elements:

https://github.com/theresaoh/blogz/blob/eb8c379028d2b69e4a9fe9b93e3b149ceb097f87/templates/blog.html#L34-L36

https://github.com/theresaoh/blogz/blob/eb8c379028d2b69e4a9fe9b93e3b149ceb097f87/templates/index.html#L10-L12

The following quote from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) informs the conventional usage of a form tag:

> The HTML \<form\> element represents a document section that contains interactive controls for submitting information to a web server.

Since these templates are not interactively submitting information to the python/flask application, the form elements are redundant and can be removed. Their contents can exist without being wrapped in form tags.

**Comment by theresaoh** [comment]
Updated!
