### ISSUE TITLE
Suggestion: Include a README.md file

### ISSUE THREAD

**Issue by seevee** [theresaoh/blogz#2]
It is considered good practice to include a README.md file in the root of each git repository. GitHub has a handy [about page](https://help.github.com/en/articles/about-readmes) for writing readme files.

Here's another guide about [mastering markdown](https://guides.github.com/features/mastering-markdown/). Markdown is the syntax used in readme files, and many applications like slack, discord, and the like also support markdown (even this issue is written in markdown!).

Here's a [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for quick reference.

A good readme should have a brief description of what the project does, as well as steps to install dependencies and run the application.

**Comment by theresaoh** [comment]
Thank you! [I added a readme file!](https://github.com/theresaoh/blogz/commit/b909798afffba2289e12693945c2caca1c04aeca)
