### ISSUE TITLE
Food for thought: Reevaluate usage of table tags

### ISSUE THREAD

**Issue by seevee** [theresaoh/blogz#3]
The table, tr, and td tags in the login template do work for basic layouts, but are intended to be used for actual tabular data. [MDN link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table).

Tables include some styling and other properties that make them useful from a templating standpoint, but the intended effect for the login page is much better implemented with CSS, particularly [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

We'll be going over CSS and the like more in depth with unit 3, so this is just an FYI! That said, you do want to be careful which tags you use - one of the web's greatest strengths is accessibility, and table tags that don't represent actual tables can be especially confusing to people using screenreaders / braille readers / etc. Here's an [informative video](https://www.youtube.com/watch?v=dEbl5jvLKGQ) demonstrating how they work.

**Comment by theresaoh** [comment]
@seevee Thank you! In my [most recent commit](https://github.com/theresaoh/blogz/commit/a8b12dc641eaeaba4228be8d9eda1c2d1366d381) I've removed tables from the login and signup pages and reworked formatting to be a bit more attractive.
